### ISSUE TITLE
Downloading TDLib...No proxy used, no response

### ISSUE THREAD

**Issue by FishOrBear** [jarvis2f/telegram-files#11]
I configured the proxy, and I can use curl google.com in bash, but after I start the container, it gets stuck.
Downloading TDLib..

```
services:
  telegram-files:
    container_name: telegram-files
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/api/health" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
    environment:
      APP_ENV: "prod"
      APP_ROOT: "./appdata/"
      TELEGRAM_API_ID: "17349"
      TELEGRAM_API_HASH: "344583e45741c457fe1862106095a5eb"
      HTTP_PROXY: "http://192.168.1.17:1080"
      HTTPS_PROXY: "http://192.168.1.17:1080"
      ALL_PROXY: "socks5h://192.168.1.17:1080"
    ports:
      - "6543:80"
    volumes:
      - /mnt/16t/p2_14t/tgfiles/

```
