### ISSUE TITLE
Bind to port 80 failed running non root

### ISSUE THREAD

**Issue by rodrigorega** [jarvis2f/telegram-files#34]
Hi,

I deleted my data directory and redeployed from the latest image (0.1.14). I got this error:

```bash
<REDACTED>:08:34.432668577Z Setting up directory permissions...
<REDACTED>:08:34.594471719Z Starting Java service...
<REDACTED>:08:34.594634507Z Starting PM2 service...
<REDACTED>:08:34.594668114Z Starting Nginx service...
<REDACTED>:08:34.881198682Z <REDACTED>:08:34 [emerg] 14#14: bind() to 0.0.0.0:80 failed (13: Permission denied)
<REDACTED>:08:39.029648312Z Setting telegram.files log level to FINE
[...]
```

I'm using the new support of `PUID` and `PGID`. Here is my `docker-compose.yml`:

```yaml
services:
  telegram-files:
    container_name: telegram-files
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://<REDACTED>:<REDACTED>/api/health" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
    environment:
      LANG: "es_ES.UTF-8"
      LANGUAGE: "es_ES:es"
      LC_ALL: "es_ES.UTF-8"
      TZ: "Europe/Madrid"
      PUID: 1070
      PGID: 100
      LOG_LEVEL: "FINE"
      TELEGRAM_LOG_LEVEL: 2
      APP_ENV: "prod"
      APP_ROOT: "/app/data"
      TELEGRAM_API_ID: "<REDACTED>"
      TELEGRAM_API_HASH: "<REDACTED>"
    ports:
      - "6543:80"
    volumes:
      - /<REDACTED>/data:/app/data
```

Maybe nginx is running as unprivileged user and can not bind to `port<1024`? I tried to run it manually as root and started ok.

Could you please help to fix this? Thanks in advance.
