### ISSUE TITLE
Feature Request: 支持评论附件下载及动态文件夹命名

### ISSUE THREAD

**Issue by fanyinrumeng** [jarvis2f/telegram-files#60]
**问题背景**  
部分Telegram频道采用以下内容分发模式：
- 主消息：图片 + 文字描述
- 实际文件：仅存在于消息评论中

当前无法实现：
1. 自动识别评论中的附件文件
2. 根据主消息内容智能分类存储
3. 保持文件与描述信息的关联性

**功能提案**  
#### 1. 评论文件检测
- 获取消息评论区附件
- 继承父级消息的元数据（描述文本、发布时间等）

#### 2. 智能分类规则
```yaml
rules:
  - pattern: "【(.*?)】"  # 匹配中括号内容作为文件夹名
    target: comments     # 针对评论区文件
    action:
      create_dir: $1     # 动态创建匹配组命名的文件夹
      move_files: [".*"] # 转移所有格式文件
```

示例场景

[主消息]
📁 项目文档更新【2023Q3财报】 
📷 截图预览...

[评论]
📎 revenue_q3.xlsx
📎 audit_report.pdf

→ 自动创建「2023Q3财报」文件夹
→ 将两个文件存入该目录
